running.mode : localhost

elasticsearch.ip : localhost
elasticsearch.port : 9200

mqtt.ip : localhost
mqtt.port : 1883
mqtt.filePersistence : false

thread.CorePoolSize : 5
thread.MaxPoolSize : 10
thread.QueueCapacity : 25
thread.ThreadNamePrefix : Data_Handler

spring.datasource.url=jdbc:postgresql://localhost:5432/Data_Analysis
spring.datasource.username=postgres
spring.datasource.password=abc
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update